Nutripro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('auth/', include('nutri_auth.urls')),
    path('',include("accounts.urls")),
    path('adminpanel/',include("adminpanel.urls")),
    path('brand/',include("brand.urls")),
    path('product/',include("product.urls")),
    path('category/',include("category.urls")),
    path('cart/', include("cart.urls")),
    path('order/', include("order.urls")),
    path('wallet/', include("wallet.urls")),
    path('coupons/',include("coupons.urls")),
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("shoppage/", views.shop_page, name="shop_page"),
    path('shop/', views.shop_ajax, name='shop-ajax'),
    path('addresses/', views.manage_addresses, name='manage_addresses'),
    path('addresses/delete/<int:pk>/', views.delete_address, name='delete_address'),
    path('my-account/', views.account_dashboard, name='dash'),
    path('add_address/', views.add_address, name='add_address'),
    path('edit_address/<int:id>/', views.edit_address, name='edit_address'),
    path('wishlist/toggle/', views.toggle_wishlist, name='toggle_wishlist'),
    path('view/', views.view_wishlist, name='wishlist'),
    path('wishlist/remove/<int:variant_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('get-counts/', views.get_counts, name='get_counts'),
    path('api/dashboard-stats/', views.get_dashboard_stats, name='dashboard_stats'),


]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    
    path('add/<int:variant_id>/', views.add_to_cart, name='add_to_cart'),
    path('view/', views.view_cart, name='view_cart'),
    path('update-cart-ajax/', views.update_cart_ajax, name='update_cart_ajax'),
    path('get-cart-summary/', views.get_cart_summary, name='get_cart_summary'),
    path('add-to-cart/<int:variant_id>/', views.add_to_cart, name='add_to_cart'),  
    path('cart/', views.view_cart, name='view_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('add/', views.add_address, name='add_address'),


]

nutri_auth/urls.py
from django.urls import path
from . import views

app_name = "nutri_auth"

urlpatterns = [
  path('signup/',views.signup,name='signup'),
  path('login/',views.handlelogin,name='handlelogin'),
  path('otp/',views.verify_otp,name='verify-otp'),
  path('resent-otp/',views.resend_otp,name='resent-otp'),
  path('logout/', views.logout_view, name='logout'),
  path('forgot-password/', views.forgot_password, name='forgot_password'),
  path('reset-password/<uidb64>/<token>/', views.reset_password, name='reset_password'),
  
]

product/urls.py
from django.urls import path
from . import views

app_name = "product"


urlpatterns = [
    path('list-product/', views.product_list, name='list-product'),
    path('addproduct/', views.add_product, name='addproduct'),
    path('add-images/', views.add_images, name='add-images'),
    path('product/<int:product_id>/edit_images/', views.edit_images, name='edit_images'),
    path('product_detail/<int:product_id>',views.product_detail,name='product-detail'),
    path('edit/<int:product_id>/', views.edit_product, name='product_edit'),
    path('image/delete/<int:image_id>/', views.delete_image, name='delete_image'),
    path('product-status/<int:pk>/', views.toggle_product_status, name='product_status'),
    path('product/variant/<int:product_id>/', views.product_variant, name='product_variant'),
    path('add_variant/<int:product_id>', views.add_variant, name='add_variant'),
    path('variant/<int:variant_id> ', views.edit_variant, name='edit_variant'),
    path('variant-status/<int:variant_id>/', views.toggle_variant_status, name='variant_status'),
    #userside
    path('product_detail_page/<int:product_id>',views.product_detail_page,name='product-detail-page'),
    path('product/delete-review/<int:review_id>/', views.delete_review, name='delete-review'),
    


]

templates/userside/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>NUTRIPRO</title>
		<!-- Include Font Awesome for star icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

		<link rel="icon" type="image/png" href="{% static 'images/nutripro.png' %}" sizes="5500x5500">
		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'userside/css/bootstrap.min.css' %}"/>

		<!-- Slick -->
		<link type="text/css" rel="stylesheet" href="{% static 'userside/css/slick.css' %}"/>
		<link type="text/css" rel="stylesheet" href="{% static 'userside/css/slick-theme.css' %}"/>

		<!-- nouislider -->
		<link type="text/css" rel="stylesheet" href="{% static 'userside/css/nouislider.min.css' %}"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'userside/css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'userside/css/style.css' %}"/>

		<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
  rel="stylesheet"
/>


		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>
	<body>
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="#"><i class="fa fa-envelope-o"></i>  {{ request.user.email }}</a></li>
					</ul>
					<ul class="header-links pull-right">
							{% if user.is_authenticated %}
									<!-- Show My Account and Logout if the user is authenticated -->
									<li><a href="{% url 'accounts:dash' %}"><i class="fa fa-user-o"></i> My Account</a></li>
									<li><a href="{% url 'nutri_auth:logout' %}"><i class="fa fa-sign-out"></i> Log Out</a></li>
							{% else %}
									<!-- Show Log In / Sign Up if the user is not authenticated -->
									<li><i class="fi-rs-user"></i><a href="{% url 'nutri_auth:handlelogin' %}">Log In</a> / <a href="{% url 'nutri_auth:signup' %}">Sign Up</a></li>
							{% endif %}
					</ul>
				</div>
			</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="{% url 'accounts:index' %}" class="logo">
									<img src="{% static 'images/nutripro.png' %}" alt="Nutripro" width="100" height="80">

								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form>
									<select class="input-select">
										<option value="0">All Categories</option>
										<option value="1">Category 01</option>
										<option value="1">Category 02</option>
									</select>
									<form id="product-filter-form">
										<input class="input" type="text" name="search" placeholder="Search products..." id="search-input">
										<button type="button" class="search-btn" id="search-button">Search</button>
									</form>
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">
							<div class="header-ctn">
								<!-- Wishlist -->
								{% comment %} <div>
									<a href="{% url 'accounts:wishlist' %}">
										<i class="fa fa-heart-o"></i>
										<span>Your Wishlist</span>
										
										<div class="qty">2</div> 
									</a>
								</div> {% endcomment %}

								<div class="wishlist-container">
									<a href="{% url 'accounts:wishlist' %}" style="position: relative; display: inline-block;">
											<i class="fa fa-heart-o" style="font-size: 24px;"></i>
											<span  id="wishlist-items" style="position: absolute; top: -16px; left: 70%; transform: translateX(-50%); color: white; background-color: red; font-size: 14px; font-weight: bold; border-radius: 50%; padding: 3px 7px;">
													{{ dashboard_stats.wishlist_items }}
											</span>
									</a>
							</div>
							
							<div class="dropdown">
									<a href="{% url 'cart:view_cart' %}">
											<i class="fa fa-shopping-cart"></i>
											<span id="cart-items" style="position: absolute; top: -16px; left: 70%; transform: translateX(-50%); color: white; background-color: red; font-size: 14px; font-weight: bold; border-radius: 50%; padding: 3px 7px;">
												{{ dashboard_stats.cart_items }}
											</span>
									</a>
							</div>
							

								{% comment %} <div class="wishlist-container">
									<a href="{% url 'accounts:wishlist' %}" style="position: relative; display: inline-block;">
										<i class="fa fa-heart-o" style="font-size: 24px;"></i>
										<span style="position: absolute; top: -16px; left: 70%; transform: translateX(-50%); color: white; background-color: red; font-size: 14px; font-weight: bold; border-radius: 50%; padding: 3px 7px;">
											{{ dashboard_stats.wishlist_items }}
										</span>
								</a>
								
							</div>
							
								<!-- /Wishlist -->

								<!-- Cart -->
								<div class="dropdown">
									<a href="{% url 'cart:view_cart' %}">
											<i class="fa fa-shopping-cart"></i>
											<span style="position: absolute; top: -16px; left: 70%; transform: translateX(-50%); color: white; background-color: red; font-size: 14px; font-weight: bold; border-radius: 50%; padding: 3px 7px;">
												{{ dashboard_stats.cart_items }}
											</span>
									</a>
								</div> {% endcomment %}
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		 

	{% block content %}

    {% endblock %}

		<!-- NEWSLETTER -->
<div id="newsletter" class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			<div class="col-md-12">
				<div class="newsletter">
					<ul class="newsletter-follow">
						<li>
							<a href="#"><i class="fa fa-facebook"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-twitter"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-instagram"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-pinterest"></i></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /NEWSLETTER -->

		<!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="#">Hot deals</a></li>
									<li><a href="#">Laptops</a></li>
									<li><a href="#">Smartphones</a></li>
									<li><a href="#">Cameras</a></li>
									<li><a href="#">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Orders and Returns</a></li>
									<li><a href="#">Terms & Conditions</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
									<li><a href="#">My Account</a></li>
									<li><a href="#">View Cart</a></li>
									<li><a href="#">Wishlist</a></li>
									<li><a href="#">Track My Order</a></li>
									<li><a href="#">Help</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->
		<script src="{% static 'userside/js/jquery.min.js' %}"></script>
		<script src="{% static 'userside/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'userside/js/slick.min.js' %}"></script>
		<script src="{% static 'userside/js/nouislider.min.js' %}"></script>
		<script src="{% static 'userside/js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'userside/js/main.js' %}"></script>

		<!-- Add SweetAlert2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            {% if messages %}
                const messages = [
                    {% for message in messages %}
                        {
                            level: "{{ message.tags }}",
                            text: "{{ message }}"
                        },
                    {% endfor %}
                ];
                messages.forEach(message => {
                    Swal.fire({
                        toast: true,
                        position: 'top-right',
                        icon: message.level === 'success' ? 'success' : 'error',
                        title: message.text,
                        showConfirmButton: false,
                        timer: 3000
                    });
                });
            {% endif %}
        });
    </script>

		<script>
			function updateDashboardStats() {
				fetch('/api/dashboard-stats/')
						.then(response => response.json())
						.then(data => {
								document.getElementById('wishlist-items').innerText = data.wishlist_items;
								document.getElementById('cart-items').innerText = data.cart_items;
						})
						.catch(error => console.error('Error fetching dashboard stats:', error));
		}

		</script>
	
	</body>
</html>

templates/userside/index.html
{% extends 'userside/base.html' %}
{% load static %}

{% block content %}

<style>
	/* Product Listing Styles */
.product-listing {
    background-color: #f8f9fa;
    min-height: 100vh;
    padding: 2rem 0;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 1rem;
}

.section-title {
    font-size: 2rem;
    font-weight: bold;
    color: #333;
    margin-bottom: 2rem;
    text-align: center;
}

.product-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    gap: 1.5rem;
}

.product-card {
    background-color: #fff;
    border-radius: 0.5rem;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    overflow: hidden;
    transition: transform 0.3s ease;
    display: flex;
    flex-direction: column;
    height: 100%;
}

.product-card:hover {
    transform: translateY(-5px);
}

.product-image {
    position: relative;
    padding-top: 100%; /* 1:1 Aspect Ratio */
    overflow: hidden;
}

.product-image img {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    object-fit: contain;
    background-color: #f8f9fa; /* Light gray background */
}

.product-info {
    padding: 1rem;
    flex-grow: 1;
    display: flex;
    flex-direction: column;
}

.product-category {
    font-size: 0.875rem;
    color: #6c757d;
    margin-bottom: 0.5rem;
}

.product-name {
    font-size: 1.125rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
}

.product-name a {
    color: #333;
    text-decoration: none;
}

.product-name a:hover {
    color: #007bff;
}

.product-price-rating {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
}

.product-price {
    font-weight: bold;
}

.current-price {
    font-size: 1.25rem;
    color: #28a745;
}

.old-price {
    font-size: 1rem;
    color: #6c757d;
    text-decoration: line-through;
    margin-left: 0.5rem;
}

.product-rating {
    color: #ffc107;
}

.product-actions {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: auto;
}

.action-buttons {
    display: flex;
    gap: 0.5rem;
}

.action-btn {
    background-color: transparent;
    border: none;
    color: #6c757d;
    cursor: pointer;
    font-size: 1rem;
    padding: 0.25rem;
    transition: color 0.3s ease;
}

.action-btn:hover {
    color: #007bff;
}

.add-to-cart-btn {
    background-color: #007bff;
    border: none;
    border-radius: 0.25rem;
    color: #fff;
    cursor: pointer;
    font-size: 0.875rem;
    padding: 0.5rem 1rem;
    transition: background-color 0.3s ease;
}

.add-to-cart-btn:hover {
    background-color: #0056b3;
}

/* Responsive adjustments */
@media (max-width: 768px) {
    .product-grid {
        grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    }
}

@media (max-width: 480px) {
    .product-grid {
        grid-template-columns: 1fr;
    }
}
</style>

<!-- NAVIGATION -->
<nav id="navigation">
	
	<!-- container -->
	<div class="container">
		<!-- responsive-nav -->
		<div id="responsive-nav">
			<!-- NAV -->
			<ul class="main-nav nav navbar-nav">
				<li class="active"><a href="{% url 'accounts:index' %}">Home</a></li>
				<li><a href="{% url 'accounts:shop_page' %}">Shop page</a></li>
				<li><a href="{% url 'accounts:shop_page' %}">Categories</a></li>
				<li><a href="{% url 'accounts:shop_page' %}">Brand</a></li>
			</ul>
			<!-- /NAV -->
		</div>
		<!-- /responsive-nav -->
	</div>
	<!-- /container -->
</nav>
<!-- /NAVIGATION -->
<!-- Product Listing Section -->
<div class="product-listing">
    <div class="container">
        <h2 class="section-title">Products</h2>
        <div class="product-grid">
            {% for item in product_data %}
            <div class="product-card">
                <a href="{% url 'product:product-detail-page' item.product.id %}" class="product-link">
                    <div class="product-image">
                        {% if item.images.exists %}
                            <img src="{{ item.images.first.images.url }}" alt="{{ item.product.Product_name }}">
                        {% else %}
                            <img src="{% static 'userside/img/default-product.png' %}" alt="Default Image">
                        {% endif %}
                    </div>
                </a>
                <div class="product-info">
                    <p class="product-category">{{ item.product.Product_category.category_name }}</p>
                    <h3 class="product-name">
                        <a href="{% url 'product:product-detail-page' item.product.id %}">
                            {{ item.product.Product_name }}
                        </a>
                    </h3>
                    <div class="product-price-rating">
                        {% if item.first_variant %}
                        <span class="current-price">₹{{ item.first_variant.offer_price }}</span>
                        <span class="old-price">₹{{ item.first_variant.price }}</span>
                    {% else %}
                        <span class="current-price">Price Not Available</span>
                    {% endif %}
                        <div class="product-rating">
                            {% for i in "12345" %}
                                <span class="star">★</span>
                            {% endfor %}
                        </div>
                    </div>

                  
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/userside/product_grid.html
{% for item in product_data %}
<div class="product-card">
    <!-- Product Image -->
    <div class="product-image">
        {% if item.images.exists %}
            <a href="{% url 'product:product-detail-page' item.product.id %}" class="product-link">
                <img src="{{ item.images.first.images.url }}" alt="{{ item.product.Product_name }}">
            </a>
        {% else %}
            {% comment %} <img src="{% static 'images/default-product.png' %}" alt="Default Image"> {% endcomment %}
        {% endif %}
        <div class="product-label">
            {% if item.variant.offer_price %}
                <span class="sale">-{{ item.variant.percentage_discount }}%</span>
            {% endif %}
            {% if item.product.is_active %}
                <span class="new">AVAILABLE</span>
            {% else %}
                <span class="new text-danger">OUT OF STOCK</span>
            {% endif %}
        </div>
    </div>

    <!-- Product Body -->
    <div class="product-body">
        <!-- Product Category -->
        <p class="product-category">
            {{ item.product.Product_category.category_name|default:"No Category" }}
        </p>

        <!-- Product Name -->
        <h3 class="product-name">
            <a href="{% url 'product:product-detail-page' item.product.id %}">
                {{ item.product.Product_name|default:"Unnamed Product" }}
            </a>
        </h3>

        <!-- Variant Information -->
        <p class="product-variant">
            {% if item.variant.size %}
                <span>Size: {{ item.variant.size }}</span>
            {% endif %}
        </p>

      <!-- Variant Price -->
    <h4 class="product-price">
        {% if item.variant and item.variant.offer_price %}
            ₹{{ item.variant.offer_price }}
        {% elif item.variant %}
            ₹{{ item.variant.price }}
        {% else %}
            Price not available
        {% endif %}
        {% if item.variant and item.variant.offer_price %}
            <del class="product-old-price">₹{{ item.variant.price }}</del>
        {% endif %}
    </h4>

        <!-- Product Rating -->
        <div class="product-rating">
            {% for i in "12345" %}
                <i class="fa fa-star"></i>
            {% endfor %}
        </div>
    </div>
</div>
{% endfor %}